//Even Fibonacci numbers
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include "../header.h"
#include "../math_functions.h"


void Problem2() {
	double sum = 0.0;
	const double kRange = 4000000;

	double fib1 = 1, fib2 = 1, fib_next = 0;

	while(1)
	{
		fib_next = fib1 + fib2;
		if(fib_next > kRange)
			break;

		if(IsEvenNum(fib_next))
			sum += fib_next;

		fib1 = fib2;
		fib2 = fib_next;
	}

	cout << sum << endl;
}