// Even Fibonacci numbers

/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence 
	whose values do not exceed four million, find the sum of the even-valued terms.

	Answer:	4613732
*/

#include "1_99.h"

bool P2()
{
	try
	{
		unsigned int sum = 0.0;
		const uint64_t kRange = 4000000;

		uint64_t fib1 = 1, fib2 = 1, fib_next = 0;

		while (1)
		{
			fib_next = fib1 + fib2;
			if (fib_next > kRange)
				break;

			if (IsEven(fib_next))
				sum += fib_next;

			fib1 = fib2;
			fib2 = fib_next;
		}

		cout << "Answer: " << sum << endl;
		return true;
	}
	catch (...)
	{
		return false;
	}
}