/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
what is the value of D?

    Answer:  5482660

*/

#include "1_99.h"

// assumimg k > j, Pk - Pj = (k-j)(3k+3j-1)/2
bool P44()
{
    try
    {
        uint64_t min_d = 0;
        vector<uint64_t> pantagon_nums;
        for (auto n = 1; n < 10000; ++n)
            pantagon_nums.push_back(PantagonNum(n));

        for (auto &pj : pantagon_nums)
        {
            for (auto &pk : pantagon_nums)
            {
                if (pj >= pk)
                    continue;
                if (min_d != 0 && pk - pj > min_d)
                    continue;
                cout << "check: " << pj << " " << pk << endl;
                bool bSum = false;
                bool bDiff = false;
                for (auto &pn : pantagon_nums)
                {
                    if (pn == pk + pj)
                        bSum = true;
                    if (pn == pk - pj)
                        bDiff = true;
                    if (bSum && bDiff)
                    {
                        min_d = pk - pj;
                        break;
                    }
                }
            }
        }

        cout << "Answer: " << min_d << endl;
        return true;
    }
    catch (...)
    {
        cout << "Exception" << endl;
        return false;
    }
}
